# Generated by Django 4.1.7 on 2023-05-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HBudgetReport', '0003_outlet_createdby_outlet_createddatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='OrganizationID',
            field=models.BigIntegerField(default=0),
        ),
    ]
