# Generated by Django 4.1.7 on 2023-05-24 09:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HBudgetReport', '0005_payrollexpenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollExpensesEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
                ('ExpenseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HBudgetReport.payrollexpenses')),
            ],
        ),
    ]
