# Generated by Django 4.1.7 on 2023-05-25 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HBudgetReport', '0006_payrollexpensesentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLUtilitiesMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('OrganizationID', models.BigIntegerField(default=0)),
                ('CreatedBy', models.BigIntegerField(default=0)),
                ('CreatedDateTime', models.DateField(default=datetime.date.today)),
                ('ModifyBy', models.BigIntegerField(default=0)),
                ('ModifyDateTime', models.DateField(default=datetime.date.today)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
